# APIs Lab

In this lab, you will work with different APIs to build datasets and perform basic analysis.

The goal is to practice how to:

- Make API requests  
- Explore JSON responses  
- Extract relevant information  
- Transform data into pandas DataFrames  
- Generate simple insights  

You will work like a data analyst using APIs data.

# Challenge 1: Pokémon Dataset & Analysis

## Goal

Build and analyze a Pokémon dataset using the API.

## Example (single request)

Below you can see how to get data for ONE Pokémon:

In [ ]:
import requests

url = "https://pokeapi.co/api/v2/pokemon/"

response = requests.get(url)
data = response.json()

data

## Tasks

1. Using the example above, get data for Pokémon IDs from 1 to 151

2. Extract:
   - name
   - height
   - weight
   - base_experience
   - first type

3. Create a DataFrame

4. Add a new column:
   - weight_kg (divide weight by 10)

5. Answer:
   - Which Pokémon is the heaviest?
   - What is the average weight?
   - How many Pokémon are there per type?

6. Answer:
   - Which type has the highest average weight?

In [47]:
import pandas as pd
import requests
pokemon = requests.get('https://pokeapi.co/api/v2/pokemon/2')
print("pokemon:", pokemon.status_code)

pokemon: 200

In [48]:
pokemon.headers

{'Date': 'Mon, 13 Apr 2026 13:46:26 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Access-Control-Allow-Origin': '*', 'cache-control': 'public, max-age=86400, s-maxage=86400', 'Report-To': '{"group":"cf-nel","max_age":604800,"endpoints":[{"url":"https://a.nel.cloudflare.com/report/v4?s=ciMK7T2V8ZNJyKtGRGWxiuBr37PH8b4TZZA8qItdY0o7vUaKpRo2bftVEZDX%2F7OrUHWTUBGmPDGDPCVo7IQMmdr4Z79aGZ%2BP4AyjgZluqQJ2SmybwRBFwZsaqmHn7j7Mo32fwKRAMKK1"}]}', 'etag': 'W/"3a208-UaeAV+hyIAKhsYxQ2HzouJGTqQg"', 'function-execution-id': 'dwpx5shyvrw4', 'Server': 'cloudflare', 'strict-transport-security': 'max-age=31556926', 'x-cloud-trace-context': '136071c8bdd03526483391f8d63ee748', 'x-country-code': 'PL', 'x-orig-accept-language': 'en-US,en;q=0.9,ru;q=0.8,ja;q=0.7,de;q=0.6,nl;q=0.5,he;q=0.4,zh-CN;q=0.3,zh;q=0.2', 'x-powered-by': 'Express', 'x-served-by': 'cache-fra-etou8220176-FRA', 'x-cache': 'HIT', 'x-cache-hits': '0', 'x-timer': 'S1769882283.006224,VS0,VE1', 'vary': 'Accept-Encoding,cookie,need-authorization, x-fh-requested-host, accept-encoding', 'alt-svc': 'h3=":443"; ma=86400', 'Nel': '{"report_to":"cf-nel","success_fraction":0.0,"max_age":604800}', 'Age': '46173', 'cf-cache-status': 'HIT', 'Content-Encoding': 'gzip', 'CF-RAY': '9ebaeab97b46ca63-TXL'}

In [49]:
data = pokemon.json()
print(data)

{'abilities': [{'ability': {'name': 'overgrow', 'url': 'https://pokeapi.co/api/v2/ability/65/'}, 'is_hidden': False, 'slot': 1}, {'ability': {'name': 'chlorophyll', 'url': 'https://pokeapi.co/api/v2/ability/34/'}, 'is_hidden': True, 'slot': 3}], 'base_experience': 142, 'cries': {'latest': 'https://raw.githubusercontent.com/PokeAPI/cries/main/cries/pokemon/latest/2.ogg', 'legacy': 'https://raw.githubusercontent.com/PokeAPI/cries/main/cries/pokemon/legacy/2.ogg'}, 'forms': [{'name': 'ivysaur', 'url': 'https://pokeapi.co/api/v2/pokemon-form/2/'}], 'game_indices': [{'game_index': 9, 'version': {'name': 'red', 'url': 'https://pokeapi.co/api/v2/version/1/'}}, {'game_index': 9, 'version': {'name': 'blue', 'url': 'https://pokeapi.co/api/v2/version/2/'}}, {'game_index': 9, 'version': {'name': 'yellow', 'url': 'https://pokeapi.co/api/v2/version/3/'}}, {'game_index': 2, 'version': {'name': 'gold', 'url': 'https://pokeapi.co/api/v2/version/4/'}}, {'game_index': 2, 'version': {'name': 'silver', 'url': 'https://pokeapi.co/api/v2/version/5/'}}, {'game_index': 2, 'version': {'name': 'crystal', 'url': 'https://pokeapi.co/api/v2/version/6/'}}, {'game_index': 2, 'version': {'name': 'ruby', 'url': 'https://pokeapi.co/api/v2/version/7/'}}, {'game_index': 2, 'version': {'name': 'sapphire', 'url': 'https://pokeapi.co/api/v2/version/8/'}}, {'game_index': 2, 'version': {'name': 'emerald', 'url': 'https://pokeapi.co/api/v2/version/9/'}}, {'game_index': 2, 'version': {'name': 'firered', 'url': 'https://pokeapi.co/api/v2/version/10/'}}, {'game_index': 2, 'version': {'name': 'leafgreen', 'url': 'https://pokeapi.co/api/v2/version/11/'}}, {'game_index': 2, 'version': {'name': 'diamond', 'url': 'https://pokeapi.co/api/v2/version/12/'}}, {'game_index': 2, 'version': {'name': 'pearl', 'url': 'https://pokeapi.co/api/v2/version/13/'}}, {'game_index': 2, 'version': {'name': 'platinum', 'url': 'https://pokeapi.co/api/v2/version/14/'}}, {'game_index': 2, 'version': {'name': 'heartgold', 'url': 'https://pokeapi.co/api/v2/version/15/'}}, {'game_index': 2, 'version': {'name': 'soulsilver', 'url': 'https://pokeapi.co/api/v2/version/16/'}}, {'game_index': 2, 'version': {'name': 'black', 'url': 'https://pokeapi.co/api/v2/version/17/'}}, {'game_index': 2, 'version': {'name': 'white', 'url': 'https://pokeapi.co/api/v2/version/18/'}}, {'game_index': 2, 'version': {'name': 'black-2', 'url': 'https://pokeapi.co/api/v2/version/21/'}}, {'game_index': 2, 'version': {'name': 'white-2', 'url': 'https://pokeapi.co/api/v2/version/22/'}}], 'height': 10, 'held_items': [], 'id': 2, 'is_default': True, 'location_area_encounters': 'https://pokeapi.co/api/v2/pokemon/2/encounters', 'moves': [{'move': {'name': 'swords-dance', 'url': 'https://pokeapi.co/api/v2/move/14/'}, 'version_group_details': [{'level_learned_at': 0, 'move_learn_method': {'name': 'machine', 'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'}, 'order': None, 'version_group': {'name': 'red-blue', 'url': 'https://pokeapi.co/api/v2/version-group/1/'}}, {'level_learned_at': 0, 'move_learn_method': {'name': 'machine', 'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'}, 'order': None, 'version_group': {'name': 'yellow', 'url': 'https://pokeapi.co/api/v2/version-group/2/'}}, {'level_learned_at': 0, 'move_learn_method': {'name': 'tutor', 'url': 'https://pokeapi.co/api/v2/move-learn-method/3/'}, 'order': None, 'version_group': {'name': 'emerald', 'url': 'https://pokeapi.co/api/v2/version-group/6/'}}, {'level_learned_at': 0, 'move_learn_method': {'name': 'tutor', 'url': 'https://pokeapi.co/api/v2/move-learn-method/3/'}, 'order': None, 'version_group': {'name': 'firered-leafgreen', 'url': 'https://pokeapi.co/api/v2/version-group/7/'}}, {'level_learned_at': 0, 'move_learn_method': {'name': 'machine', 'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'}, 'order': None, 'version_group': {'name': 'diamond-pearl', 'url': 'https://pokeapi.co/api/v2/version-group/8/'}}, {'level_learned_at': 0, 'move_learn_method': {'name': 'machine', 'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'}, 'order': None, 'version_group': {'name': 'platinum', 'url': 'https://pokeapi.co/api/v2/version-group/9/'}}, {'level_learned_at': 0, 'move_learn_method': {'name': 'machine', 'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'}, 'order': None, 'version_group': {'name': 'heartgold-soulsilver', 'url': 'https://pokeapi.co/api/v2/version-group/10/'}}, {'level_learned_at': 0, 'move_learn_method': {'name': 'machine', 'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'}, 'order': None, 'version_group': {'name': 'black-white', 'url': 'https://pokeapi.co/api/v2/version-group/11/'}}, {'level_learned_at': 0, 'move_learn_method': {'name': 'machine', 'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'}, 'order': None, 'version_group': {'name': 'black-2-white-2', 'url': 'https://pokeapi.co/api/v2/version-group/14/'}}, {'level_learned_at': 0, 'move_learn_method': {'name': 'machine', 'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'}, 'order': None, 'version_group': {'name': 'x-y', 'url': 'https://pokeapi.co/api/v2/version-group/15/'}}, {'level_learned_at': 0, 'move_learn_method': {'name': 'machine', 'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'}, 'order': None, 'version_group': {'name': 'omega-ruby-alpha-sapphire', 'url': 'https://pokeapi.co/api/v2/version-group/16/'}}, {'level_learned_at': 0, 'move_learn_method': {'name': 'machine', 'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'}, 'order': None, 'version_group': {'name': 'sun-moon', 'url': 'https://pokeapi.co/api/v2/version-group/17/'}}, {'level_learned_at': 0, 'move_learn_method': {'name': 'machine', 'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'}, 'order': None, 'version_group': {'name': 'ultra-sun-ultra-moon', 'url': 'https://pokeapi.co/api/v2/version-group/18/'}}, {'level_learned_at': 0, 'move_learn_method': {'name': 'machine', 'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'}, 'order': None, 'version_group': {'name': 'sword-shield', 'url': 'https://pokeapi.co/api/v2/version-group/20/'}}, {'level_learned_at': 0, 'move_learn_method': {'name': 'machine', 'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'}, 'order': None, 'version_group': {'name': 'brilliant-diamond-shining-pearl', 'url': 'https://pokeapi.co/api/v2/version-group/23/'}}, {'level_learned_at': 0, 'move_learn_method': {'name': 'machine', 'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'}, 'order': None, 'version_group': {'name': 'scarlet-violet', 'url': 'https://pokeapi.co/api/v2/version-group/25/'}}, {'level_learned_at': 0, 'move_learn_method': {'name': 'machine', 'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'}, 'order': None, 'version_group': {'name': 'red-green-japan', 'url': 'https://pokeapi.co/api/v2/version-group/28/'}}, {'level_learned_at': 0, 'move_learn_method': {'name': 'machine', 'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'}, 'order': None, 'version_group': {'name': 'blue-japan', 'url': 'https://pokeapi.co/api/v2/version-group/29/'}}]}, {'move': {'name': 'cut', 'url': 'https://pokeapi.co/api/v2/move/15/'}, 'version_group_details': [{'level_learned_at': 0, 'move_learn_method': {'name': 'machine', 'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'}, 'order': None, 'version_group': {'name': 'red-blue', 'url': 'https://pokeapi.co/api/v2/version-group/1/'}}, {'level_learned_at': 0, 'move_learn_method': {'name': 'machine', 'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'}, 'order': None, 'version_group': {'name': 'yellow', 'url': 'https://pokeapi.co/api/v2/version-group/2/'}}, {'level_learned_at': 0, 'move_learn_method': {'name': 'machine', 'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'}, 'order': None, 'version_group': {'name': 'gold-silver', 'url': 'https://pokeapi.co/api/v2/version-group/3/'}}, {'level_learned_at': 0, 'move_learn_method': {'name': 'machine', 'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'}, 'order': None, 'version_group': {'name': 'crystal', 'url': 'https://pokeapi.co/api/v2/version-group/4/'}}, {'level_learned_at': 0, 'move_learn_method': {'name': 'machine', 'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'}, 'order': None, 'version_group': {'name': 'ruby-sapphire', 'url': 'https://pokeapi.co/api/v2/version-group/5/'}}, {'level_learned_at': 0, 'move_learn_method': {'name': 'machine', 'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'}, 'order': None, 'version_group': {'name': 'emerald', 'url': 'https://pokeapi.co/api/v2/version-group/6/'}}, {'level_learned_at': 0, 'move_learn_method': {'name': 'machine', 'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'}, 'order': None, 'version_group': {'name': 'firered-leafgreen', 'url': 'https://pokeapi.co/api/v2/version-group/7/'}}, {'level_learned_at': 0, 'move_learn_method': {'name': 'machine', 'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'}, 'order': None, 'version_group': {'name': 'diamond-pearl', 'url': 'https://pokeapi.co/api/v2/version-group/8/'}}, {'level_learned_at': 0, 'move_learn_method': {'name': 'machine', 'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'}, 'order': None, 'version_group': {'name': 'platinum', 'url': 'https://pokeapi.co/api/v2/version-group/9/'}}, {'level_learned_at': 0, 'move_learn_method': {'name': 'machine', 'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'}, 'order': None, 'version_group': {'name': 'heartgold-soulsilver', 'url': 'https://pokeapi.co/api/v2/version-group/10/'}}, {'level_learned_at': 0, 'move_learn_method': {'name': 'machine', 'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'}, 'order': None, 'version_group': {'name': 'black-white', 'url': 'https://pokeapi.co/api/v2/version-group/11/'}}, {'level_learned_at': 0, 'move_learn_method': {'name': 'machine', 'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'}, 'order': None, 'version_group': {'name': 'colosseum', 'url': 'https://pokeapi.co/api/v2/version-group/12/'}}, {'level_learned_at': 0, 'move_learn_method': {'name': 'machine', 'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'}, 'order': None, 'version_group': {'name': 'xd', 'url': 'https://pokeapi.co/api/v2/version-group/13/'}}, {'level_learned_at': 0, 'move_learn_method': {'name': 'machine', 'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'}, 'order': None, 'version_group': {'name': 'black-2-white-2', 'url': 'https://pokeapi.co/api/v2/version-group/14/'}}, {'level_learned_at': 0, 'move_learn_method': {'name': 'machine', 'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'}, 'order': None, 'version_group': {'name': 'x-y', 'url': 'https://pokeapi.co/api/v2/version-group/15/'}}, {'level_learned_at': 0, 'move_learn_method': {'name': 'machine', 'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'}, 'order': None, 'version_group': {'name': 'omega-ruby-alpha-sapphire', 'url': 'https://pokeapi.co/api/v2/version-group/16/'}}, {'level_learned_at': 0, 'move_learn_method': {'name': 'machine', 'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'}, 'order': None, 'version_group': {'name': 'brilliant-diamond-shining-pearl', 'url': 'https://pokeapi.co/api/v2/version-group/23/'}}, {'level_learned_at': 0, 'move_learn_method': {'name': 'machine', 'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'}, 'order': None, 'version_group': {'name': 'red-green-japan', 'url': 'https://pokeapi.co/api/v2/version-group/28/'}}, {'level_learned_at': 0, 'move_learn_method': {'name': 'machine', 'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'}, 'order': None, 'version_group': {'name': 'blue-japan', 'url': 'https://pokeapi.co/api/v2/version-group/29/'}}]}, {'move': {'name': 'bind', 'url': 'https://pokeapi.co/api/v2/move/20/'}, 'version_group_details': [{'level_learned_at': 0, 'move_learn_method': {'name': 'tutor', 'url': 'https://pokeapi.co/api/v2/move-learn-method/3/'}, 'order': None, 'version_group': {'name': 'black-2-white-2', 'url': 'https://pokeapi.co/api/v2/version-group/14/'}}, {'level_learned_at': 0, 'move_learn_method': {'name': 'tutor', 'url': 'https://pokeapi.co/api/v2/move-learn-method/3/'}, 'order': None, 'version_group': {'name': 'omega-ruby-alpha-sapphire', 'url': 'https://pokeapi.co/api/v2/version-group/16/'}}, {'level_learned_at': 0, 'move_learn_method': {'name': 'tutor', 'url': 'https://pokeapi.co/api/v2/move-learn-method/3/'}, 'order': None, 'version_group': {'name': 'ultra-sun-ultra-moon', 'url': 'https://pokeapi.co/api/v2/version-group/18/'}}]}, {'move': {'name': 'vine-whip', 'url': 'https://pokeapi.co/api/v2/move/22/'}, 'version_group_details': [{'level_learned_at': 13, 'move_learn_method': {'name': 'level-up', 'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'}, 'order': None, 'version_group': {'name': 'red-blue', 'url': 'https://pokeapi.co/api/v2/version-group/1/'}}, {'level_learned_at': 13, 'move_learn_method': {'name': 'level-up', 'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'}, 'order': None, 'version_group': {'name': 'yellow', 'url': 'https://pokeapi.co/api/v2/version-group/2/'}}, {'level_learned_at': 10, 'move_learn_method': {'name': 'level-up', 'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'}, 'order': None, 'version_group': {'name': 'gold-silver', 'url': 'https://pokeapi.co/api/v2/version-group/3/'}}, {'level_learned_at': 10, 'move_learn_method': {'name': 'level-up', 'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'}, 'order': None, 'version_group': {'name': 'crystal', 'url': 'https://pokeapi.co/api/v2/version-group/4/'}}, {'level_learned_at': 10, 'move_learn_method': {'name': 'level-up', 'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'}, 'order': None, 'version_group': {'name': 'ruby-sapphire', 'url': 'https://pokeapi.co/api/v2/version-group/5/'}}, {'level_learned_at': 10, 'move_learn_method': {'name': 'level-up', 'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'}, 'order': None, 'version_group': {'name': 'emerald', 'url': 'https://pokeapi.co/api/v2/version-group/6/'}}, {'level_learned_at': 10, 'move_learn_method': {'name': 'level-up', 'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'}, 'order': None, 'version_group': {'name': 'firered-leafgreen', 'url': 'https://pokeapi.co/api/v2/version-group/7/'}}, {'level_learned_at': 9, 'move_learn_method': {'name': 'level-up', 'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'}, 'order': None, 'version_group': {'name': 'diamond-pearl', 'url': 'https://pokeapi.co/api/v2/version-group/8/'}}, {'level_learned_at': 9, 'move_learn_method': {'name': 'level-up', 'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'}, 'order': None, 'version_group': {'name': 'platinum', 'url': 'https://pokeapi.co/api/v2/version-group/9/'}}, {'level_learned_at': 9, 'move_learn_method': {'name': 'level-up', 'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'}, 'order': None, 'version_group': {'name': 'heartgold-soulsilver', 'url': 'https://pokeapi.co/api/v2/version-group/10/'}}, {'level_learned_at': 9, 'move_learn_method': {'name': 'level-up', 'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'}, 'order': None, 'version_group': {'name': 'black-white', 'url': 'https://pokeapi.co/api/v2/version-group/11/'}}, {'level_learned_at': 10, 'move_learn_method': {'name': 'level-up', 'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'}, 'order': None, 'version_group': {'name': 'colosseum', 'url': 'https://pokeapi.co/api/v2/version-group/12/'}}, {'level_learned_at': 10, 'move_learn_method': {'name': 'level-up', 'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'}, 'order': None, 'version_group': {'name': 'xd', 'url': 'https://pokeapi.co/api/v2/version-group/13/'}}, {'level_learned_at': 9, 'move_learn_method': {'name': 'level-up', 'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'}, 'order': None, 'version_group': {'name': 'black-2-white-2', 'url': 'https://pokeapi.co/api/v2/version-group/14/'}}, {'level_learned_at': 9, 'move_learn_method': {'name': 'level-up', 'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'}, 'order': None, 'version_group': {'name': 'x-y', 'url': 'https://pokeapi.co/api/v2/version-group/15/'}}, {'level_learned_at': 9, 'move_learn_method': {'name': 'level-up', 'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'}, 'order': None, 'version_group': {'name': 'omega-ruby-alpha-sapphire', 'url': 'https://pokeapi.co/api/v2/version-group/16/'}}, {'level_learned_at': 9, 'move_learn_method': {'name': 'level-up', 'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'}, 'order': None, 'version_group': {'name': 'sun-moon', 'url': 'https://pokeapi.co/api/v2/version-group/17/'}}, {'level_learned_at': 9, 'move_learn_method': {'name': 'level-up', 'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'}, 'order': None, 'version_group': {'name': 'ultra-sun-ultra-moon', 'url': 'https://pokeapi.co/api/v2/version-group/18/'}}, {'level_learned_at': 1, 'move_learn_method': {'name': 'level-up', 'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'}, 'order': 3, 'version_group': {'name': 'lets-go-pikachu-lets-go-eevee', 'url': 'https://pokeapi.co/api/v2/version-group/19/'}}, {'level_learned_at': 5, 'move_learn_method': {'name': 'level-up', 'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'}, 'order': None, 'version_group': {'name': 'lets-go-pikachu-lets-go-eevee', 'url': 'https://pokeapi.co/api/v2/version-group/19/'}}, {'level_learned_at': 1, 'move_learn_method': {'name': 'level-up', 'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'}, 'order': 3, 'version_group': {'name': 'sword-shield', 'url': 'https://pokeapi.co/api/v2/version-group/20/'}}, {'level_learned_at': 1, 'move_learn_method': {'name': 'level-up', 'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'}, 'order': 4, 'version_group': {'name': 'brilliant-diamond-shining-pearl', 'url': 'https://pokeapi.co/api/v2/version-group/23/'}}, {'level_learned_at': 1, 'move_learn_method': {'name': 'level-up', 'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'}, 'order': 1, 'version_group': {'name': 'scarlet-violet', 'url': 'https://pokeapi.co/api/v2/version-group/25/'}}, {'level_learned_at': 13, 'move_learn_method': {'name': 'level-up', 'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'}, 'order': None, 'version_group': {'name': 'red-green-japan', 'url': 'https://pokeapi.co/api/v2/version-group/28/'}}, {'level_learned_at': 13, 'move_learn_method': {'name': 'level-up', 'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'}, 'order': None, 'version_group': {'name': 'blue-japan', 'url': 'https://pokeapi.co/api/v2/version-group/29/'}}]}, {'move': {'name': 'headbutt', 'url': 'https://pokeapi.co/api/v2/move/29/'}, 'version_group_details': [{'level_learned_at': 0, 'move_learn_method': {'name': 'machine', 'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'}, 'order': None, 'version_group': {'name': 'gold-silver', 'url': 'https://pokeapi.co/api/v2/version-group/3/'}}, {'level_learned_at': 0, 'move_learn_method': {'name': 'machine', 'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'}, 'order': None, 'version_group': {'name': 'crystal', 'url': 'https://pokeapi.co/api/v2/version-group/4/'}}, {'level_learned_at': 0, 'move_learn_method': {'name': 'tutor', 'url': 'https://pokeapi.co/api/v2/move-learn-method/3/'}, 'order': None, 'version_group': {'name': 'heartgold-soulsilver', 'url': 'https://pokeapi.co/api/v2/version-group/10/'}}, {'level_learned_at': 0, 'move_learn_method': {'name': 'machine', 'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'}, 'order': None, 'version_group': {'name': 'lets-go-pikachu-lets-go-eevee', 'url': 'https://pokeapi.co/api/v2/version-group/19/'}}]}, {'move': {'name': 'tackle', 'url': 'https://pokeapi.co/api/v2/move/33/'}, 'version_group_details': [{'level_learned_at': 1, 'move_learn_method': {'name': 'level-up', 'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'}, 'order': 1, 'version_group': {'name': 'red-blue', 'url': 'https://pokeapi.co/api/v2/version-group/1/'}}, {'level_learned_at': 1, 'move_learn_method': {'name': 'level-up', 'url': 'https://pokeapi.co

In [50]:
data.keys()

dict_keys(['abilities', 'base_experience', 'cries', 'forms', 'game_indices', 'height', 'held_items', 'id', 'is_default', 'location_area_encounters', 'moves', 'name', 'order', 'past_abilities', 'past_stats', 'past_types', 'species', 'sprites', 'stats', 'types', 'weight'])

In [51]:
print(list(data.keys()))

['abilities', 'base_experience', 'cries', 'forms', 'game_indices', 'height', 'held_items', 'id', 'is_default', 'location_area_encounters', 'moves', 'name', 'order', 'past_abilities', 'past_stats', 'past_types', 'species', 'sprites', 'stats', 'types', 'weight']

In [58]:
name = data['species']["name"]

In [59]:
height = data['height']

In [60]:
weight = data['weight']

In [61]:
base_experience = data['base_experience']

In [67]:
first_type =  data['types'][0]['type']['name']

In [ ]:
import requests
import pandas as pd

def get_pokemon_data(id):
    url = f"https://pokeapi.co/api/v2/pokemon/{id}/"
    r = requests.get(url)
    data = r.json()
    weight = int(data['weight'])
    return {
        "name": data['name'],  # or data['species']['name']
        "height": data['height'],
        "weight": weight,
        "base_experience": data.get('base_experience'),
        "first_type": data['types'][0]['type']['name'],
        "weight_kg": weight / 10.0
    }

ids = range(1, 152)
rows = [get_pokemon_data(i) for i in ids]

df = pd.DataFrame(rows, columns=["name", "height", "weight", "base_experience", "first_type", "weight_kg"])
print(df)

           name  height  weight  base_experience first_type  weight_kg
0     bulbasaur       7      69               64      grass        6.9
1       ivysaur      10     130              142      grass       13.0
2      venusaur      20    1000              236      grass      100.0
3    charmander       6      85               62       fire        8.5
4    charmeleon      11     190              142       fire       19.0
..          ...     ...     ...              ...        ...        ...
145     moltres      20     600              261       fire       60.0
146     dratini      18      33               60     dragon        3.3
147   dragonair      40     165              147     dragon       16.5
148   dragonite      22    2100              270     dragon      210.0
149      mewtwo      20    1220              306    psychic      122.0

[150 rows x 6 columns]

In [75]:
pokemon_list = []
for i in range(1, 152):
    url = f"https://pokeapi.co/api/v2/pokemon/{i}"
    response = requests.get(url)
    data = response.json()
    pokemon_list.append ({
        "name": data["name"],
        "height": data['height'],
        "weight": data['weight'], 
        "base_experience": data["base_experience"],
        "first_type": data['types'][0]['type']['name']
    })
df = pd.DataFrame(pokemon_list)
df['weight_kg'] = df["weight"]/10
df

           name  height  weight  base_experience first_type  weight_kg
0     bulbasaur       7      69               64      grass        6.9
1       ivysaur      10     130              142      grass       13.0
2      venusaur      20    1000              236      grass      100.0
3    charmander       6      85               62       fire        8.5
4    charmeleon      11     190              142       fire       19.0
..          ...     ...     ...              ...        ...        ...
146     dratini      18      33               60     dragon        3.3
147   dragonair      40     165              147     dragon       16.5
148   dragonite      22    2100              270     dragon      210.0
149      mewtwo      20    1220              306    psychic      122.0
150         mew       4      40              270    psychic        4.0

[151 rows x 6 columns]

# Challenge 2: Crypto Market Analysis

## Goal

Analyze cryptocurrency prices using real-time data.

## Tasks

1. Get prices for:
   - bitcoin
   - ethereum
   - solana
   - dogecoin

2. Convert the response into a DataFrame (coins as rows)

3. Rename columns properly

4. Add:
   - price_rank (ranking by price)
   - price_category:
        - "high" if > 1000  
        - "medium" if between 100 and 1000  
        - "low" if < 100  

5. Answer:
   - Which coin is the most expensive?
   - Which category has more coins?

6. **Bonus**:
   - Create a column with price difference vs bitcoin

In [ ]:
# starter code

import requests
import pandas as pd
import numpy as np

url = "https://api.coingecko.com/api/v3/simple/price"

params = {"ids": "bitcoin,ethereum,solana,dogecoin",
    "vs_currencies": "usd",
    "include_market_cap": "true",
}
# params = {
#     "ids": "bitcoin,ethereum,solana,dogecoin",
#     "vs_currencies": "usd"
# }

In [52]:
cr = requests.get(url, params=params)
cr.headers

{'Date': 'Fri, 17 Apr 2026 09:00:00 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Server': 'cloudflare', 'x-frame-options': 'SAMEORIGIN', 'x-xss-protection': '0', 'x-content-type-options': 'nosniff', 'x-permitted-cross-domain-policies': 'none', 'referrer-policy': 'strict-origin-when-cross-origin', 'Cache-Control': 'max-age=30, public, must-revalidate, s-maxage=60', 'access-control-allow-origin': '*', 'access-control-allow-methods': 'POST, PUT, DELETE, GET, OPTIONS', 'access-control-request-method': '*', 'access-control-allow-headers': 'Origin, X-Requested-With, Content-Type, Accept, Authorization', 'access-control-expose-headers': 'link, per-page, total', 'vary': 'Accept-Encoding, Origin', 'Content-Encoding': 'gzip', 'etag': 'W/"d0e0fa7ffa2186b84811ed35d1354b30"', 'x-request-id': 'ea8e849a-0dd7-471a-89dd-33b2bd1925ff', 'x-runtime': '0.006251', 'alternate-protocol': '443:npn-spdy/2', 'content-security-policy-report-only': 'script-src https://accounts.google.com/gsi/client; frame-src https://accounts.google.com/gsi/; connect-src https://accounts.google.com/gsi/;', 'strict-transport-security': 'max-age=15724800; includeSubdomains', 'cf-cache-status': 'MISS', 'CF-RAY': '9eda3ca91b8ac760-TXL', 'alt-svc': 'h3=":443"; ma=86400'}

In [53]:
crypto = cr.json()
print(crypto)

{'bitcoin': {'usd': 75739, 'usd_market_cap': 1516620163362.3523}, 'dogecoin': {'usd': 0.09849, 'usd_market_cap': 15171245313.88597}, 'ethereum': {'usd': 2355.06, 'usd_market_cap': 284232545354.6686}, 'solana': {'usd': 88.93, 'usd_market_cap': 51155759628.5184}}

In [54]:
crypto['bitcoin']

{'usd': 75739, 'usd_market_cap': 1516620163362.3523}

In [58]:
df_cr = pd.DataFrame.from_dict(crypto, orient="index").reset_index().rename(columns={"index":"coin_name", "usd": "price_usd", "usd_market_cap": "generated_value"})

print(df_cr)

  coin_name    price_usd  generated_value
0   bitcoin  75739.00000     1.516620e+12
1  dogecoin      0.09849     1.517125e+10
2  ethereum   2355.06000     2.842325e+11
3    solana     88.93000     5.115576e+10

In [61]:
df_cr['price_usd'] = pd.to_numeric(df_cr['price_usd'], errors='coerce')

df_cr['price_rank'] = df_cr['price_usd'].rank(method='dense', ascending=False).astype('Int64')

conds = [
    df_cr['price_usd'] > 1000,
    df_cr['price_usd'].between(100, 1000, inclusive='both'),
    df_cr['price_usd'] < 100
]
choices = ['high', 'medium', 'low']


df_cr['price_category'] = np.select(conds, choices, default='unknown')

print(df_cr)

  coin_name    price_usd  generated_value  price_rank price_category
0   bitcoin  75739.00000     1.516620e+12           1           high
1  dogecoin      0.09849     1.517125e+10           4            low
2  ethereum   2355.06000     2.842325e+11           2           high
3    solana     88.93000     5.115576e+10           3            low

In [63]:
most_expensive = df_cr.loc[df_cr['price_usd'].idxmax()]
most_expensive_name = most_expensive['coin_name']
most_expensive_price = most_expensive['price_usd']
print(f"The most expensive coin is {most_expensive_name} with price {most_expensive_price} USD")

The most expensive coin is bitcoin with price 75739.0 USD

In [67]:
counts = df_cr['price_category'].value_counts(dropna=True)
top_category, top_count = counts.idxmax(), counts.max()
print(f" In category - {top_category} there are {top_count} coin types")

 In category - high there are 2 coin types

In [69]:
btc_mask = df_cr['coin_name'].str.lower() == 'bitcoin'
if not btc_mask.any():
    raise KeyError("Bitcoin row not found in df_cr['coin_name']")
btc_price = df_cr.loc[btc_mask, 'price_usd'].iloc[0]
if pd.isna(btc_price):
    raise ValueError("Bitcoin price is NaN")

# absolute difference (positive means coin is more expensive than BTC)
df_cr['diff_vs_bitcoin'] = df_cr['price_usd'] - btc_price
df_cr

,coin_name,price_usd,generated_value,price_rank,price_category,diff_vs_bitcoin
0,bitcoin,75739.00000,1.516620e+12,1,high,0.00000
1,dogecoin,0.09849,1.517125e+10,4,low,-75738.90151
2,ethereum,2355.06000,2.842325e+11,2,high,-73383.94000
3,solana,88.93000,5.115576e+10,3,low,-75650.07000